# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d0902eef0b088f6119cbebc70320b7b6cf9607995e1dd6a4874cc0716eb999e86dcda15f3aa6d17dcdc4285ad2248b021f93560b943ff4f4f93ba5e1a3c7f9

test:
  secret_key_base: de8fb06c527a42f56327ba6b33d31e3aba80834757a94250e2facc0144c9cf6010e92941bdabcb03201fe734b957c211e8d1a08b89acf595be899ff9f2e54592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
